### ISSUE TITLE
[Feature request]Have the option to be able to choose between runit and openrc during installation

### ISSUE THREAD

**Issue by emanuelserpa** [artix-linux/artix-linux.github.io#10]

**Comment by udeved** [comment]
That is not possible in calamares and they way it does things..

**Comment by emanuelserpa** [comment]
Well, it's not like is possible atm to have a functional system with runit on Artix.

I hope that this will change.

**Comment by ghost** [comment]
Perhaps alpine linux insterested by you

**Comment by emanuelserpa** [comment]
No, doesn't interest me. Alpine is not like Arch.

**Comment by ghost** [comment]
So, consult [this](http://without-systemd.org/wiki/index.php/Main_Page) and perhaps you find something relevant for you
