### ISSUE TITLE
Website 2/3 links don't work

### ISSUE THREAD

**Issue by edwardando** [artix-linux/artix-linux.github.io#3]
For me on https://artix-linux.github.io/
both "Install" and "Why?" links go to a 404 page.

**Comment by ghost** [comment]
Suggestion: put comments in [systemd-free](http://systemd-free.org/)

**Comment by cromerc** [comment]
This is already known, the webpage for artix is still under construction. I will leave this open for now so that nobody else reports the same problem.

**Comment by cromerc** [comment]
I am going to close this considering that we moved to artixlinux.org
