### ISSUE TITLE
reboot, halt and powerooff don't print nothing

### ISSUE THREAD

**Issue by ghost** [artix-linux/artix-linux.github.io#8]
When I run these commands, I get nothing in screen.

**Comment by cromerc** [comment]
Which tty are you on?
The messages get printed to tty1.

_Sent from my Motorola Moto G (4) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
tty1 is busy with X. With Arch I have X in tty7 but with Artix it moves to tty1. In Arch it prints in whereever tty you are.

**Comment by cromerc** [comment]
What dm and de do you use?

_Sent from my Motorola Moto G (4) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
DM? LXDM

**Comment by cromerc** [comment]
DM is display manager, and DE is desktop environment. I assume LXDE with LXDM?

**Comment by udeved** [comment]
LXDM starts by default on VT1, but it needs to be set to VT7 in lxdm.conf.

**Comment by cromerc** [comment]
Should we maybe rebuild LXDM and change it to default to VT1?

**Comment by udeved** [comment]
We should probably build all common DMs as soon as jenkins does its job.
Currently, we only build sddm.

**Comment by cromerc** [comment]
Sounds like a plan to me.

**Comment by ghost** [comment]
I have XFCE and LXDE with LXDM. Both have the same behaviour. I just get output if I halt (or reboot...) using lxdm button. All other options (halt from tty, halt from xfce or lxde) cause no output

**Comment by ghost** [comment]
With `sddm` it works. I changed this file:
```
$ cat /etc/conf.d/xdm 
# We always try and start X on a static VT. The various DMs normally default
# to using VT7. If you wish to use the xdm init script, then you should ensure
# that the VT checked is the same VT your DM wants to use. We do this check to
# ensure that you haven't accidentally configured something to run on the VT
# in your /etc/inittab file so that you don't get a dead keyboard.
CHECKVT=7

# What display manager do you use ?  [ xdm | gdm | kdm | gpe | entrance ]
# NOTE: If this is set in /etc/rc.conf, that setting will override this one.
DISPLAYMANAGER="sddm"
# estava a lxdm
```

and it's ok. But with `lxdm` instead, X is in tty1. So it seems a lxdm related problem.

**Comment by ghost** [comment]
Confirmed: it's lxdm related bug. In `/etc/lxdm/lxdm.conf` I have:
```
[server]
## arg used to start xserver, not fully function
arg=/usr/bin/X -background vt1
```

Change this to vt7 makes it works. So you change the package configuration or something in artix linux.
