### ISSUE TITLE
I discovered packages from arch

### ISSUE THREAD

**Issue by ghost** [artix-linux/artix-linux.github.io#9]
I discovered I have `xf86-input-synpatics` from arch not from artix. Immediately I replaced the package.

Is there any way to know what packages I have in `extra` or `community` and replace them for packages in `system`, `world` and `galaxy`?

It would prevent mixing environments (arch and artix).

**Comment by cromerc** [comment]
Sorry for the late reply, there isn't any way to know which repo the package was installed from. As the fork continues and we keep adding more and more packages we will depend less and less on arch's repos. Until then we just have to be patient and keep an eye manually on where stuff comes from.
